import {useEffect,useMemo,useState} from "react";
import {BookOpen,Download,FileText,CheckCircle2,XCircle} from "lucide-react";
import API from "../../services/api";import {useClientAuth} from "../../context/ClientAuthContext";import toast from "react-hot-toast";
const ORIGIN=(import.meta.env.VITE_API_BASE_URL||"").replace(/\/api\/?$/,'');
export default function ClientSOPLibrary(){const {client}=useClientAuth();const isEmployee=client?.role==='CLIENT_EMPLOYEE';const [rows,setRows]=useState([]),[dept,setDept]=useState(''),[loading,setLoading]=useState(true);
 const load=async()=>{try{const r=await API.get('/sops/client-library');setRows(Array.isArray(r.data)?r.data:[])}catch(e){toast.error('Failed to load work policies / SOPs')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const departments=useMemo(()=>[...new Set(rows.map(r=>r.department).filter(Boolean))].sort(),[rows]);const filtered=dept?rows.filter(r=>r.department===dept):rows;
 const download=async s=>{try{const target=s.download_url||s.files?.[0]?.download_url||s.file_url;if(!target)throw 0;const r=await fetch(ORIGIN+target);if(!r.ok)throw 0;const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=s.file_name||s.files?.[0]?.file_name||`${s.title}.pdf`;a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch{toast.error('Download failed')}};
 const decision=async(s,status)=>{let note='';if(status==='rejected'){note=window.prompt('Why are you rejecting this SOP?','')||'';if(!note.trim())return toast.error('Rejection note is required')}try{await API.post(`/sops/client-library/${s.id}/decision`,{status,note});toast.success(status==='accepted'?'SOP accepted':'SOP rejected');load()}catch(e){toast.error(e?.response?.data?.message||'Action failed')}};
 return <div className="space-y-6"><div className="flex flex-col sm:flex-row sm:justify-between gap-4"><div className="flex gap-3.5"><div className="w-11 h-11 rounded-2xl bg-indigo-50 flex items-center justify-center"><BookOpen className="text-indigo-600" size={20}/></div><div><h1 className="text-2xl md:text-3xl font-bold text-slate-900">{isEmployee?'SOP Library':'SOP Library'}</h1><p className="text-sm text-slate-500 mt-1">{isEmployee?'Read every client SOP and accept or reject it with a note when required.':'Client SOPs and work policies visible to your employees.'}</p></div></div><select value={dept} onChange={e=>setDept(e.target.value)} className="px-3.5 py-2.5 rounded-xl border border-slate-200 bg-white text-sm"><option value="">All departments</option>{departments.map(d=><option key={d}>{d}</option>)}</select></div>
 {loading?<div className="p-12 text-center text-slate-400">Loading...</div>:!filtered.length?<div className="card-premium p-12 text-center text-slate-400">No client SOPs published yet.</div>:<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">{filtered.map(s=><div key={s.id} className="card-premium p-5 flex flex-col gap-3"><div className="flex gap-3"><div className="w-10 h-10 rounded-xl bg-violet-50 flex items-center justify-center"><FileText className="text-violet-600" size={18}/></div><div><h3 className="font-bold text-slate-900">{s.title}</h3><p className="text-xs text-slate-400">{s.department||'General'} • v{s.current_version}</p></div></div>{s.description&&<p className="text-sm text-slate-500 leading-relaxed">{s.description}</p>}{isEmployee&&s.employee_decision&&<div className={`rounded-xl p-3 text-xs ${s.employee_decision==='accepted'?'bg-emerald-50 text-emerald-700':'bg-rose-50 text-rose-700'}`}>{s.employee_decision==='accepted'?'Accepted':'Rejected'}{s.employee_note?` • ${s.employee_note}`:''}</div>}<div className="mt-auto flex gap-2"><button disabled={!s.file_url} onClick={()=>download(s)} className="flex-1 inline-flex justify-center items-center gap-2 px-3 py-2.5 rounded-xl bg-indigo-600 text-white text-xs font-semibold disabled:opacity-40"><Download size={14}/> PDF</button>{isEmployee&&<><button onClick={()=>decision(s,'accepted')} className="px-3 py-2.5 rounded-xl bg-emerald-50 text-emerald-700 text-xs font-semibold"><CheckCircle2 size={15}/></button><button onClick={()=>decision(s,'rejected')} className="px-3 py-2.5 rounded-xl bg-rose-50 text-rose-700 text-xs font-semibold"><XCircle size={15}/></button></>}</div></div>)}</div>}
 </div>}
