"""
Ardhnarishwar SaaS - Live SQLAlchemy Runtime Verification Script
Executes real SQLAlchemy ORM transactions, table creations, foreign keys, indexes, and queries.
"""
import os
import sys
from datetime import datetime, timedelta

# Add backend directory to sys.path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from sqlalchemy import create_engine, select, func
from sqlalchemy.orm import sessionmaker

from app.core.database import Base
from app.models import (
    Company,
    Subscription,
    User,
    AuditLog,
    Job,
    InterviewRound,
    QuestionBank,
    round_questions,
    Candidate,
    InterviewSession,
    CandidateAnswer,
    AIEvaluationReport
)
from app.crud.interview_crud import (
    get_candidates_by_tenant,
    get_candidate_by_token,
    get_session_evaluation_dossier,
    create_job_position,
    create_interview_round_with_questions,
    get_platform_telemetry
)

def run_live_sqlalchemy_verification():
    print("=" * 70)
    print("  EXECUTING LIVE SQLALCHEMY ORM RUNTIME & DATABASE QUERIES TEST")
    print("=" * 70)

    # 1. Initialize Engine (Using echo=True to display raw SQL generated by SQLAlchemy)
    # Using local test database to demonstrate immediate executable verification
    test_db_url = "sqlite:///./ardhnarishwar_runtime_test.db"
    if os.path.exists("./ardhnarishwar_runtime_test.db"):
        os.remove("./ardhnarishwar_runtime_test.db")
        
    print(f"\n[STEP 1] Creating SQLAlchemy Engine with Connection Pooling:")
    print(f"- Target URI: {test_db_url}")
    print(f"- Engine Driver: SQLite / MySQL Compatible Dialect")
    
    engine = create_engine(test_db_url, echo=False)
    Session = sessionmaker(bind=engine)
    db = Session()

    # 2. Generate Schema & Tables
    print(f"\n[STEP 2] Creating All ORM Tables with Foreign Keys & Indexes:")
    Base.metadata.create_all(engine)
    table_names = list(Base.metadata.tables.keys())
    print(f"- Successfully Created {len(table_names)} Tables:")
    for t in sorted(table_names):
        print(f"  • {t}")

    # 3. Seed Companies & Users
    print(f"\n[STEP 3] Inserting Multi-Tenant Entities & Committing Transaction:")
    ardhnarishwar = Company(
        id="comp_ardhnarishwar",
        name="Ardhnarishwar HQ Global",
        slug="ardhnarishwar",
        domain="ardhnarishwar.ai",
        plan_tier="ENTERPRISE_ROBOTICS",
        status="ACTIVE",
        contact_email="hq@ardhnarishwar.ai",
        contact_person="Platform Director",
        industry="Enterprise AI",
        ai_custom_rules_enabled=True
    )
    
    cyberdyne = Company(
        id="comp_cyberdyne",
        name="Cyberdyne Autonomous Systems",
        slug="cyberdyne",
        domain="cyberdyne.io",
        plan_tier="ENTERPRISE_ROBOTICS",
        status="ACTIVE",
        contact_email="talent@cyberdyne.io",
        contact_person="Dr. Miles Bennett",
        industry="Defense & Autonomous Robotics",
        ai_custom_rules_enabled=True
    )

    boston_bio = Company(
        id="comp_boston_bio",
        name="Boston BioRobotics Tech",
        slug="boston-biorobotics",
        domain="bostonbiorobotics.com",
        plan_tier="GROWTH",
        status="ACTIVE",
        contact_email="recruiting@bostonbiorobotics.com",
        contact_person="Elena Rostova",
        industry="Surgical Robotics",
        ai_custom_rules_enabled=False
    )
    
    db.add_all([ardhnarishwar, cyberdyne, boston_bio])
    db.commit()
    print("[PASS] Companies inserted and committed.")

    # 4. Insert Job & Questions
    job_robotics = create_job_position(
        db=db,
        company_id="comp_cyberdyne",
        title="Lead Robotics Controls Engineer",
        department="Autonomous Perception & SLAM",
        location="San Francisco, CA (Hybrid)",
        experience_level="LEAD",
        description="Design high-performance kinematics controllers...",
        required_skills=["Kinematics", "Singularity Avoidance", "ROS 2", "C++ 20"]
    )

    q1 = QuestionBank(
        id="q_kinematics_01",
        category="TECHNICAL",
        role_category="Robotics & Controls",
        difficulty="HARD",
        title="Kinematics & Singularity Avoidance",
        prompt="Explain Forward vs Inverse Kinematics and Jacobian singularity avoidance...",
        expected_duration_sec=120,
        ideal_benchmark_answer="Forward kinematics computes Cartesian pose using DH parameters...",
        key_concepts=["Forward Kinematics", "Inverse Kinematics", "Denavit-Hartenberg", "Jacobian Matrix"],
        anti_patterns=["Ignoring singularities"],
        rubric_weights={"relevance": 0.35, "technical": 0.45, "communication": 0.20},
        is_global=True
    )
    db.add(q1)
    db.commit()

    # Link to round
    round1 = create_interview_round_with_questions(
        db=db,
        company_id="comp_cyberdyne",
        job_id=job_robotics.id,
        name="Technical Robotics & Kinematics Round",
        round_type="TECHNICAL_ROBOTICS",
        time_limit_minutes=25,
        passing_score=75.0,
        question_ids=[q1.id]
    )
    print(f"[PASS] Created Job '{job_robotics.title}' and Round '{round1.name}' linked via association table.")

    # 5. Insert Candidate, Session, Answer & Evaluation Report
    priya = Candidate(
        id="cand_priya_01",
        company_id="comp_cyberdyne",
        job_id=job_robotics.id,
        first_name="Priya",
        last_name="Sharma",
        email="priya.sharma@gmail.com",
        phone="+1 (408) 723-9901",
        current_title="Senior Robotics Engineer",
        years_of_experience=6,
        status="EVALUATED",
        interview_token="TOKEN_PRIYA_LIVE_DEMO"
    )
    db.add(priya)
    db.commit()

    session_priya = InterviewSession(
        id="sess_priya_01",
        company_id="comp_cyberdyne",
        candidate_id=priya.id,
        job_id=job_robotics.id,
        round_id=round1.id,
        started_at=datetime.utcnow() - timedelta(minutes=20),
        completed_at=datetime.utcnow(),
        status="COMPLETED",
        overall_score=88.5,
        recommendation="STRONG_HIRE",
        video_storage_path="s3://ardhnarishwar-media/videos/sess_priya_01.mp4"
    )
    db.add(session_priya)
    db.flush()

    ans1 = CandidateAnswer(
        id="ans_priya_01",
        session_id=session_priya.id,
        question_id=q1.id,
        video_timestamp_start=0,
        video_timestamp_end=115,
        transcript="Forward kinematics uses DH parameters to calculate Cartesian pose. Inverse kinematics calculates joint angles. Singularities happen when Jacobian determinant rank drops...",
        duration_sec=28,
        score=91.0,
        feedback="Strong conceptual grasp. Covered core principles.",
        relevance_score=88.0,
        technical_score=94.0,
        communication_score=100.0,
        problem_solving_score=85.0,
        confidence_score=90.0,
        role_competency_score=91.0,
        identified_concepts=["Forward Kinematics", "Inverse Kinematics", "Denavit-Hartenberg", "Jacobian Matrix"],
        missing_concepts=[],
        filler_word_count=0,
        wpm=132,
        speech_hesitation_ratio=0.0
    )

    report_priya = AIEvaluationReport(
        id="rep_priya_01",
        session_id=session_priya.id,
        candidate_id=priya.id,
        ai_model_version_id="aiv_v3_4_0_robotics",
        overall_score=88.5,
        recommendation="STRONG_HIRE",
        relevance_avg=88.0,
        technical_avg=94.0,
        communication_avg=100.0,
        problem_solving_avg=85.0,
        confidence_avg=90.0,
        role_competency_avg=91.0,
        strengths=["Exemplary mastery of Jacobian rank decomposition", "Crisp delivery at 132 WPM"],
        weaknesses=[],
        red_flags=[],
        executive_summary="Candidate demonstrates top-percentile robotics control competence.",
        model_version_snapshot={"version_tag": "v3.4.0-robotics-core"},
        reproducibility_hash="hash_priya_live_verified"
    )

    db.add_all([ans1, report_priya])
    db.commit()
    print("[PASS] Candidate session, answer timestamps, and AI evaluation report committed.")

    # ==============================================================================
    # RUNTIME QUERY DEMONSTRATION & ASSERTIONS
    # ==============================================================================
    print("\n" + "=" * 70)
    print("  RUNTIME SQLALCHEMY QUERY VERIFICATION")
    print("=" * 70)

    # Query 1: Tenant-isolated candidate query
    print("\n[RUNTIME QUERY 1] Tenant-Isolated Candidate Query:")
    cyberdyne_candidates = get_candidates_by_tenant(db, "comp_cyberdyne")
    print(f"SQL Pattern: SELECT * FROM candidates WHERE company_id = 'comp_cyberdyne'")
    print(f"- Retrieved Candidates Count: {len(cyberdyne_candidates)}")
    for c in cyberdyne_candidates:
        print(f"  * {c.first_name} {c.last_name} | Job: {c.job.title} | Status: {c.status}")

    assert len(cyberdyne_candidates) == 1, "Should retrieve Cyberdyne candidate"

    # Query 2: Cross-Tenant Data Isolation Test
    print("\n[RUNTIME QUERY 2] Cross-Tenant Security Leakage Check:")
    boston_candidates = get_candidates_by_tenant(db, "comp_boston_bio")
    print(f"SQL Pattern: SELECT * FROM candidates WHERE company_id = 'comp_boston_bio'")
    print(f"- Boston Bio Candidates (Expected 0): {len(boston_candidates)}")
    assert len(boston_candidates) == 0, "Boston Bio cannot see Cyberdyne candidates"
    print("[PASS] Cross-tenant query protection validated: 0 foreign records returned.")

    # Query 3: Eager-Loaded Session Scorecard & Video Bookmarks
    print("\n[RUNTIME QUERY 3] Complex Eager-Loaded Scorecard & Video Replay Query:")
    dossier = get_session_evaluation_dossier(db, "comp_cyberdyne", priya.id)
    print(f"- Candidate: {dossier.candidate.first_name} {dossier.candidate.last_name}")
    print(f"- AI Recommendation: {dossier.recommendation} (Score: {dossier.overall_score}/100)")
    print(f"- Video Storage Path: {dossier.video_storage_path}")
    print(f"- Synchronized Question Answers ({len(dossier.answers)}):")
    for a in dossier.answers:
        print(f"  * Q: '{a.question.title}' | Video: {a.video_timestamp_start}s - {a.video_timestamp_end}s | Score: {a.score}/100")

    assert dossier.overall_score == 88.5, "Dossier score mismatch"
    assert len(dossier.answers) == 1, "Answers not eager-loaded"

    # Query 4: Super Admin Telemetry Aggregation
    print("\n[RUNTIME QUERY 4] Super Admin Global SQL Aggregations:")
    telemetry = get_platform_telemetry(db)
    print(f"- Total Companies: {telemetry['total_companies']}")
    print(f"- Total Candidates Evaluated: {telemetry['total_candidates']}")
    print(f"- Platform Average Score: {telemetry['platform_average_score']}%")
    print(f"- Top Tenant Breakdown: {telemetry['hiring_breakdown']}")

    print("\n" + "=" * 70)
    print("  ALL SQLALCHEMY ORM RUNTIME QUERIES & RELATIONSHIPS VERIFIED 100%!")
    print("=" * 70 + "\n")

    db.close()

if __name__ == "__main__":
    run_live_sqlalchemy_verification()
