import express from "express";
import multer from "multer";
import fs from "fs";
import path from "path";
import { getAssignments,createAssignment,updateAssignment,deleteAssignment,updateStatus,listAssignmentDeliverables,createAssignmentDeliverable } from "./workAssignment.controller.js";
import { clientUnifiedAuthMiddleware } from "../../../middleware/clientUnifiedAuth.middleware.js";
import { clientAuthMiddleware } from "../../../middleware/clientAuth.middleware.js";
const router=express.Router();
const DEST="uploads/assignment-deliverables";
const storage=multer.diskStorage({destination:(req,file,cb)=>{fs.mkdirSync(DEST,{recursive:true});cb(null,DEST)},filename:(req,file,cb)=>cb(null,`${Date.now()}-${Math.round(Math.random()*1e9)}${path.extname(file.originalname).toLowerCase()}`)});
const upload=multer({storage,limits:{fileSize:500*1024*1024}});
router.use(clientUnifiedAuthMiddleware);
router.get("/",getAssignments);
router.get("/:id/deliverables",listAssignmentDeliverables);
router.post("/",clientAuthMiddleware,createAssignment);
router.put("/:id",clientAuthMiddleware,updateAssignment);
router.delete("/:id",clientAuthMiddleware,deleteAssignment);
router.patch("/status/:id",updateStatus);
router.post("/:id/deliverables",upload.single("file"),createAssignmentDeliverable);
export default router;
