import {
  Users,
  CalendarDays,
  ClipboardList,
  Wallet,
  BarChart3,
  LayoutGrid,
  MessageCircle,
  TrendingUp,
  FileText,
  Target,
  FileBarChart,
  DollarSign,
  TrendingDown,
  BookOpen,
  Package,
  Building2,
  ShoppingCart,
  Receipt,
  FileBarChart2,
  History,
  AlertCircle,
  Handshake,
} from "lucide-react";

export const CLIENT_MENU = [
  {
    key: "OVERVIEW",
    label: "Overview",
    path: "/overview",
    icon: LayoutGrid,
  },
  {
    key: "PROPOSALS",
    label: "Proposals",
    path: "/proposals",
    icon: Handshake,
  },
  {
    key: "EMPLOYEE_MANAGEMENT",
    label: "Employee Management",
    path: "/employees",
    icon: Users,
  },
  {
    key: "SOP_LIBRARY",
    label: "SOP Library",
    path: "/sop-library",
    icon: BookOpen,
  },
  {
    key: "LEAVE_APPROVALS",
    label: "Leave Approvals",
    path: "/leave-approvals",
    icon: CalendarDays,
  },
  {
    key: "OFFER_LETTERS",
    label: "Offer Letters",
    path: "/offer-letters",
    icon: FileText,
  },
  {
    key: "EMPLOYEE_SEARCH",
    label: "Employee Search",
    path: "/employee-search",
    icon: Users,
  },
  {
    key: "ATTENDANCE_TRACKER",
    label: "Attendance Tracker",
    path: "/attendance",
    icon: CalendarDays,
  },

  {
    key: "PAYROLL",
    label: "Payroll",
    path: "/payroll",
    icon: Wallet,
  },
  {
    key: "SALES_REPORT",
    label: "Sales Report",
    path: "/sales-report",
    icon: BarChart3,
  },
  {
    key: "LIVE_CHAT",
    label: "Live Chat",
    path: "/chat",
    icon: MessageCircle,
  },
  {
    key: "PERFORMANCE_TRACKER",
    label: "Performance",
    path: "/performance",
    icon: TrendingUp,
  },
  {
    key: "PERFORMANCE_REPORT",
    label: "Performance Report",
    path: "/performance-report",
    icon: FileBarChart,
  },
  {
    key: "WORK_POLICY",
    label: "Work Policy",
    path: "/work-policy",
    icon: FileText,
  },
  {
    key: "WORK_ASSIGNMENT",
    label: "Work Assignment",
    path: "/work-assignment",
    icon: ClipboardList,
  },
  // {
  //   key: "WORK_TARGET",
  //   label: "Work Target",
  //   path: "/work-target",
  //   icon: Target,
  // },
  {
    key: "FINANCE_DASHBOARD",
    label: "Finance Dashboard",
    path: "/expenses",
    icon: DollarSign,
  },
  // {
  //   key: "LEDGER",
  //   label: "General Ledger",
  //   path: "/finance/ledger",
  //   icon: BookOpen,
  // },
  {
    key: "INVENTORY",
    label: "Inventory",
    path: "/finance/inventory",
    icon: Package,
  },
  {
    key: "ASSETS",
    label: "Assets",
    path: "/finance/assets",
    icon: Building2,
  },
  {
    key: "PURCHASE_ORDERS",
    label: "Purchase Orders",
    path: "/finance/purchase-orders",
    icon: ShoppingCart,
  },
  {
    key: "TAX",
    label: "GST & TDS",
    path: "/finance/tax",
    icon: Receipt,
  },
  {
    key: "AUDIT_LOGS",
    label: "Audit Logs",
    path: "/finance/audit-logs",
    icon: History,
  },
    {
    key: "COMPLAINT",
    label: "Complaint Box",
    path: "/complaint",
    icon: AlertCircle,
  },

      {
    key: "LEADS",
    label: "Leads Assigner",
    path: "/leads",
    icon: AlertCircle,
  },

];
